#!/bin/bash

run_name="$1"

for i in "1" "2" "3" "4" "5" "6" "7" "8" "9" "10" "11" "13" "14" "15" "16" "17" "18" "19" "20" "21" "22" "25"; do
    echo "---- $run_name ----" >> "./$i/out"
    echo "---- $run_name ----" >> "./$i/err"
    { time trilogy run "./$i/p1.tri" < "./$i/input" ; } 2>> "./$i/err" >> "./$i/out"
    if [ -f "./$i/p2.tri" ]
        { time trilogy run "./$i/p2.tri" < "./$i/input" ; } 2>> "./$i/err" >> "./$i/out"
    fi
done
