name:                p2

dependencies:
- base >= 4.7 && < 5
- split >= 0.2

executables:
  main:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
